image: python:2.7

before_script:
  - uname -r
  - which python
  - python --version
  - apt-get update -y
  - apt-get install iverilog -y
  - source etc/tmrg.sh

test_help:
    script: 
        - tmrg --help

test_examples:
    script: 
        - cd examples
        - ../tests/run_all.py 

