image: python:2.7

test_help:
    script: 
        - which python
        - python --version
        - source etc/tmrg.sh
        - tmrg --help

test_examples:
    script: 
        - cd examples
        - ../tests/run_all.py 

