image: python:2.7

before_script:
  - apt-get update -y
  - apt-get install iverilog -y

test_help:
    script: 
        - uname -r
        - which python
        - python --version
        - source etc/tmrg.sh
        - tmrg --help

test_examples:
    script: 
        - cd examples
        - ../tests/run_all.py 

