image: python:2.7

before_script:
  - uname -r
  - which python
  - python --version
  - apt-get update -y
  - apt-get install iverilog python-coverage -y
  - source etc/tmrg.sh


test:
    script: 
        - tmrg --help
        - cd tests/enabled
        - ../run_all.py 
# coverage regexp : ^\[INFO\s+\]\s+\|\s+\TOTAL\s+\d+\s+\d+\s+(\d+\%)
