#image: python:2.7

#before_script:
#  - uname -r
#  - which python
#  - python --version
#  - apt-get update -y
#  - apt-get install iverilog python-coverage -y
#  - source etc/tmrg.sh


test_ubuntu:
   image: ubuntu:latest
   script: 
        - apt-get update -y
        - apt-get install iverilog python-coverage -y
#        - apt-get install build-essential -y
        - source etc/tmrg.sh
        - tmrg --help
        - cd tests/
        - ./scripts/regression.py
#        - make

#test_centos6:
#   image: centos:6
#   script: 
#        - yum -y install  python-coverage iverilog
##        - apt-get install iverilog python-coverage -y
##        - apt-get install build-essential -y
#        - source etc/tmrg.sh
#        - tmrg --help
#        - cd tests/
#        - ./scripts/regression.py
##        - make

#test_slc6:
#    image: cern/slc6-base
#    script: 
#        - yum -y install  python-coverage
##        - apt-get install iverilog python-coverage -y
##        - apt-get install build-essential -y
#        - source etc/tmrg.sh
#        - tmrg --help
#        - cd tests/
#        - ./scripts/regression.py
##        - make

# coverage regexp : ^\[INFO\s+\]\s+\|\s+\TOTAL\s+\d+\s+\d+\s+(\d+\%)
