# Point to you systemC Install Dir
SYSTEMC_HOME = /appl/systemc
INC_OPT      = -I. -I$(VCS_HOME)/include \
	       -I$(SYSTEMC_HOME)/include
COMP_OPT     = -c 
LIB_OPT      = $(SYSTEMC_HOME)/lib-linux/libsystemc.a
CPP_FILE     = counter.cpp counter_tb.cpp 
DPI_C_FILE   = counter_dpi.c
V_FILE       = counter.sv

DPI_O_FILE   = counter.o counter_dpi.o counter_tb.o
VCS_OPT      = -CFLAGS -lstdc++ $(LIB_OPT)

dpi:c cpp
	vcs -sverilog $(DPI_O_FILE) counter.sv $(VCS_OPT) -R

cpp : $(CPP_FILE)
	gcc $(INC_OPT) $(COMP_OPT) $(CPP_FILE)

c : $(DPI_C_FILE)
	gcc $(INC_OPT) $(COMP_OPT) $(DPI_C_FILE)

clean:
	rm -rf *.o simv csrc simv.daidir vcs.key *.vpd *.vcd \
	vc_hdrs.h
